### ISSUE TITLE
You should not expose your zsh history like that, better make this project private :)

### ISSUE THREAD

**Issue by Alfagun74** [SwayKh/dotfiles#1]

**Comment by SwayKh** [comment]
Okay, I removed the file from history, should be fine now.

Can I ask what the issue is with the history? I kept it since I can check my history with fzf's Ctrl-R bind.

**Comment by Alfagun74** [comment]
It's fine to keep it on your computer, but just make sure not to make it publicly available on GitHub. I've had some OpSec issues in the past because of things like this, so I go around warning people. Terminal histories can contain sensitive information like usernames, keys, passwords, and file/folder structures—things you don't want exposed.

My suggestion is to make the repository private and download a ZIP via the Git UI whenever you need it. Just a friendly tip to help protect your information.

Have a nice day! :)

**Comment by SwayKh** [comment]
Thanks for the insight, I'll keep it in mind.
