### ISSUE TITLE
Linksys.yaml source file and destination file should be reverse

### ISSUE THREAD

**Issue by i0day** [SwayKh/dotfiles#2]
I see you put symbolic link into dotfiles directory. Is it supposed to use dotfiles as source and the destination /home/user/.config/ should have symbolic link to dotfiles? Not the other way around. Nice theme by the way

**Comment by SwayKh** [comment]
Correct me if I'm wrong, I might be misunderstanding what you're saying. 

The Source and Destinations are defined by Linksym. Which I'd say is declared more from the process of it.

Linksym, takes a file from the *Source* (.config/whatever) and moves it to the *destination*, which is the dotfiles directory and creates a symlink at the *source* pointing towards *destination*. It doesn't use the naming from the results, as you say, where the dotfiles directory is the *source* of configs.

And thanks for the compliment about the theme, which I just noticed I forgot to update the screenshots, as I've moved to using kanagawa.nvim theme and colors on my system

**Comment by i0day** [comment]
Thank you for your reply,I am kind of confuse of it, because I git clone your dotfiles into ~/river/dotfiles, 

Run linksym update and linksym source. The first time it might work fine, but since it does not copy the scripts 

directory, I manually clone your scripts into dotfiles. and run linksym update and linksym source again. 

Now I got lots of errors, and it creates a symbolic link  ~/river/dotfiles/river/river  which is pointing to it self. my .config/river is empty now. 

so I am kind of confuse of what it does, does it remove all the file in the .config and create a symbolic link into .config/
point to the dotfiles directory, how come i got a  ~/river/dotfiles/river/river which is symbolic link in the dotfiles?

**Comment by i0day** [comment]
I actually want to install your dotfiles, not move my ./config all into dotfiles directory.

If I need to backup my .config as my dotfiles I am suppose to do that. But to install your dotfiles is to move your files to my .config/  or create a symbolic link in .config/ point to your dotfiles

Do I get it right? Please advise.

**Comment by i0day** [comment]
To achieve the setup where files from ~/river/dotfiles are symlinked into ~/.config, you need to adjust the entries in your .linksym.yaml file so that the source is in ~/river/dotfiles and the target is in ~/.config.

Here’s how you can adjust your .linksym.yaml:
init_directory: ~/river/dotfiles
records:
    - name: dotfiles/btop
      paths:
        - $init_directory/btop
        - ~/.config/btop
    - name: dotfiles/cava
      paths:
        - $init_directory/cava
        - ~/.config/cava
    - name: dotfiles/dunst
      paths:
        - $init_directory/dunst
        - ~/.config/dunst
    - name: dotfiles/fastfetch
      paths:
        - $init_directory/fastfetch
        - ~/.config/fastfetch
    - name: dotfiles/foot
      paths:
        - $init_directory/foot
        - ~/.config/foot
    - name: dotfiles/hypr
      paths:
        - $init_directory/hypr
        - ~/.config/hypr
    - name: dotfiles/i3
      paths:
        - $init_directory/i3
        - ~/.config/i3
    - name: dotfiles/kitty
      paths:
        - $init_directory/kitty
        - ~/.config/kitty
    - name: dotfiles/lf
      paths:
        - $init_directory/lf
        - ~/.config/lf
    - name: dotfiles/micro
      paths:
        - $init_directory/micro
        - ~/.config/micro
    - name: dotfiles/neofetch
      paths:
        - $init_directory/neofetch
        - ~/.config/neofetch
    - name: dotfiles/nvim
      paths:
        - $init_directory/nvim
        - ~/.config/nvim
    - name: dotfiles/polybar
      paths:
        - $init_directory/polybar
        - ~/.config/polybar
    - name: dotfiles/river
      paths:
        - $init_directory/river
        - ~/.config/river
    - name: dotfiles/rofi
      paths:
        - $init_directory/rofi
        - ~/.config/rofi
    - name: dotfiles/sway
      paths:
        - $init_directory/sway
        - ~/.config/sway
    - name: dotfiles/swayidle
      paths:
        - $init_directory/swayidle
        - ~/.config/swayidle
    - name: dotfiles/swaylock
      paths:
        - $init_directory/swaylock
        - ~/.config/swaylock
    - name: dotfiles/tmux
      paths:
        - $init_directory/tmux
        - ~/.config/tmux
    - name: dotfiles/waybar
      paths:
        - $init_directory/waybar
        - ~/.config/waybar
    - name: dotfiles/wezterm
      paths:
        - $init_directory/wezterm
        - ~/.config/wezterm
    - name: dotfiles/yazi
      paths:
        - $init_directory/yazi
        - ~/.config/yazi
    - name: share/applications
      paths:
        - $init_directory/.local/share/applications
        - ~/.local/share/applications
    - name: ES-DE/es_settings.xml
      paths:
        - $init_directory/ES-DE/es_settings.xml
        - ~/ES-DE/settings/es_settings.xml
    - name: RetroArch/retroarch.cfg
      paths:
        - $init_directory/RetroArch/retroarch.cfg
        - ~/.config/retroarch/retroarch.cfg
    - name: RetroArch/retroarch-core-options.cfg
      paths:
        - $init_directory/RetroArch/retroarch-core-options.cfg
        - ~/.config/retroarch/retroarch-core-options.cfg
    - name: dotfiles/starship.toml
      paths:
        - $init_directory/starship.toml
        - ~/.config/starship.toml
    - name: dotfiles/.bashrc
      paths:
        - $init_directory/.bashrc
        - ~/.bashrc
    - name: dotfiles/.gitconfig
      paths:
        - $init_directory/.gitconfig
        - ~/.gitconfig
    - name: dotfiles/.profile
      paths:
        - $init_directory/.profile
        - ~/.profile
    - name: dotfiles/.ripgreprc
      paths:
        - $init_directory/.ripgreprc
        - ~/.ripgreprc
    - name: dotfiles/.zshrc
      paths:
        - $init_directory/.zshrc
        - ~/.zshrc
    - name: dotfiles/.zsh_history.bak
      paths:
        - $init_directory/.zsh_history.bak
        - ~/.zsh_history.bak
    - name: dotfiles/home.gitignore
      paths:
        - $init_directory/home.gitignore
        - ~/home.gitignore
    - name: dotfiles/.vimrc
      paths:
        - $init_directory/.vimrc
        - ~/.vimrc
    - name: dotfiles/mimeapps.list
      paths:
        - $init_directory/mimeapps.list
        - ~/.config/mimeapps.list
    - name: Code/settings.json
      paths:
        - $init_directory/Code/settings.json
        - ~/.config/Code/User/settings.json
This is the advise taken from chatgpt

**Comment by SwayKh** [comment]
Can you create an issue on linksym.

I did find this bug when testing, and it should be fixed. But I'll do some more testing to see if I can reproduce this bug.

The latest linksym release was 2 days ago, are you using the latest version?

If that doesn't fix it, please open an issue on linksym, which the necessary details

**Comment by SwayKh** [comment]
Hey @i0day.
Did your issue get fixed? Can you provide some updates.

I'd like to know if there is some bug with linksym or not.

**Comment by i0day** [comment]
I have not try anything new because I am kind of confused what the linksym does. So it create a symbolic link in the .config directory point to your dot files? All I need to do is to update the file in dot file directory right?在 2025年1月2日，上午3:41，Sumit Khatri ***@***.***> 写道：﻿
Hey @i0day.
Did your issue get fixed? Can you provide some updates.
I'd like to know if there is some bug with linksym or not.

**Comment by SwayKh** [comment]
yeah, that's what a symlink does. It's a special file that points to another file on the file system. 

Linksym's main purpose is to create those symlinks AND create record for it, to make it easier to reproduce the symlinks in one step.

You can also give the linkdots.sh scripts a try, It does still work, I'll just not be updating it with future symlink records, but It does have all the major configs links.

Be sure to back up your .config/ for programs
